"""Feedback-informed action prioritisation for each submitted guest profile.

This service uses aspect-risk signals generated by scripts/20_train_review_feedback_nlp.py.
It deliberately does not claim that review data contains historical staff-action
labels; NLP detects real guest pain points, then ranks operational actions that
are relevant to the current guest's stated needs.
"""

from pathlib import Path
import json


ROOT = Path(__file__).resolve().parents[2]
INTELLIGENCE_PATH = ROOT / "data" / "processed" / "review_feedback_action_intelligence.json"


class ReviewFeedbackActionService:
    def __init__(self):
        self.risk_by_aspect = {}
        if INTELLIGENCE_PATH.exists():
            payload = json.loads(INTELLIGENCE_PATH.read_text(encoding="utf-8"))
            self.risk_by_aspect = {
                item["aspect"]: float(item["negativeMentionRate"])
                for item in payload.get("aspects", [])
            }

    def top_feedback_aspects(self, count=4):
        return [
            {"aspect": aspect, "negativeMentionRate": rate}
            for aspect, rate in sorted(self.risk_by_aspect.items(), key=lambda item: item[1], reverse=True)[:count]
        ]

    def recommend(self, guest, preferences, purpose):
        if not self.risk_by_aspect:
            return None

        def interest(name):
            return float(preferences.get(f"{name}_Interest", 1)) / 5

        children = int(guest.get("children") or 0)
        stay = int(guest.get("stayDuration") or 1)
        candidates = [
            ("Verify the reserved room, cleanliness, and comfort setup before arrival", "Room", max(0.45, interest("Family"), interest("Wellness")), "Room quality is a high-impact pre-arrival check."),
            ("Assign a named arrival contact and confirm check-in details", "Staff service", 0.65 if purpose in {"Business", "Honeymoon"} else 0.48, "A clear arrival handover reduces service friction."),
            ("Confirm dietary dining options and reserve a suitable meal time", "Food", max(interest("Food"), 0.82 if guest.get("foodPreference") else 0.25), "The plan is tailored to the guest's dining needs."),
            ("Test Wi-Fi and prepare a practical workspace before check-in", "Facilities", 0.96 if purpose == "Business" else 0.42, "Reliable facilities are particularly important for this stay context."),
            ("Prepare a quiet, restorative room and offer wellness timings", "Wellness", max(interest("Wellness"), 0.9 if purpose == "Wellness" else 0.2), "The guest profile indicates a restorative stay preference."),
            ("Confirm family room layout, child amenities, and activity timings", "Room", max(interest("Family"), 0.94 if children else 0.2), "Family context requires a suitable shared-room setup."),
            ("Share transport, distance, and local-area guidance before arrival", "Location", max(interest("Nature"), interest("Culture"), 0.45 if stay >= 3 else 0.2), "Location information supports a smoother experience outside the hotel."),
            ("Confirm transparent value details, inclusions, and any extra charges", "Value", 0.78 if guest.get("budget") == "Low" else 0.36, "Clear cost communication supports the stated budget."),
        ]
        if guest.get("accessibilityNeeds"):
            candidates.append(("Review accessibility requirements with the assigned arrival contact", "Facilities", 1.0, "Accessibility support was explicitly requested."))
        if interest("Adventure") >= 0.8:
            candidates.append(("Confirm activity transport, timing, safety, and weather details", "Staff service", interest("Adventure"), "Adventure is one of the guest's strongest preferences."))

        ranked = []
        for action, aspect, relevance, guest_reason in candidates:
            feedback_risk = self.risk_by_aspect.get(aspect, 0)
            score = round(min(96, 46 + relevance * 37 + min(feedback_risk, 45) * 0.28))
            ranked.append({
                "action": action,
                "match": score,
                "reason": f"{guest_reason} Real review NLP found {feedback_risk:.1f}% of negative feedback mentions related to {aspect.lower()}.",
                "feedbackAspect": aspect,
                "feedbackRisk": feedback_risk,
            })
        ranked.sort(key=lambda item: item["match"], reverse=True)
        seen, actions = set(), []
        for item in ranked:
            if item["action"] not in seen:
                actions.append(item)
                seen.add(item["action"])
            if len(actions) == 5:
                break
        return {
            "source": "Real Booking.com feedback NLP action prioritiser (100,000 reviews)",
            "actions": actions,
        }


review_feedback_action_service = ReviewFeedbackActionService()
